import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UtilService {

  imageSrc: { name: string, path: string }[] = [];

  constructor() {
    this.imageSrc.push({name: 'HP ProBook 440 G8 Notebook (i5 with Win10 Pro)', path: './assets/images/homepage/laptop/1.png'});
    this.imageSrc.push({name: 'HP ProBook 440 G8 Notebook (i5)', path: './assets/images/homepage/laptop/2.png'});
    this.imageSrc.push({name: 'HP ProBook 450 G8 Notebook (Win10, i7)', path: './assets/images/homepage/laptop/3.png'});
    this.imageSrc.push({name: 'Dell Inspiron 5502 (i5)', path: './assets/images/homepage/laptop/4.png'});
    this.imageSrc.push({name: 'Dell Inspiron 5502 (i7)', path: './assets/images/homepage/laptop/5.png'});
    this.imageSrc.push({name: 'Dell G3 3500 – i7 (16GB RAM)', path: './assets/images/homepage/laptop/6.png'});
    this.imageSrc.push({name: 'Acer Aspire 3 A315 (AMD Athlon)', path: './assets/images/homepage/laptop/7.png'});
    this.imageSrc.push({name: 'ACER Aspire A515 – i5 1135G7', path: './assets/images/homepage/laptop/8.png'});
    this.imageSrc.push({name: 'ACER A515 i3 1115G4 (DOS)', path: './assets/images/homepage/laptop/9.png'});
    this.imageSrc.push({name: 'Asus Tuf Gaming FX506 HN117T (RTX Graphics)', path: './assets/images/homepage/laptop/10.png'});
    this.imageSrc.push({name: 'Asus Tuf Gaming FX506 HN117T (GTX Graphics)', path: './assets/images/homepage/laptop/11.png'});
    this.imageSrc.push({name: 'ASUS ROG Flow X13', path: './assets/images/homepage/laptop/12.png'});
    this.imageSrc.push({name: 'Apple MacBook Air MGNE3LL/A (Gold – Late 2020)', path: './assets/images/homepage/laptop/13.png'});
    this.imageSrc.push({name: 'Apple MYD82LL/A 13.3-inch MacBook Pro (Space Gray)', path: './assets/images/homepage/laptop/14.png'});
    this.imageSrc.push({name: 'Apple MacBook Air (MGN63LL/A | MGN93LL/A | MGND3LL/A)', path: './assets/images/homepage/laptop/15.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A22 6GB RAM 128GB', path: './assets/images/homepage/laptop/11.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M32 8GB RAM 128GB', path: './assets/images/homepage/phone/2.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M42 5G', path: './assets/images/homepage/phone/3.png'});
    this.imageSrc.push({name: 'Nokia C20 2GB RAM 32GB', path: './assets/images/homepage/phone/4.png'});
    this.imageSrc.push({name: 'Nokia 5.4 4GB RAM 128GB', path: './assets/images/homepage/phone/5.png'});
    this.imageSrc.push({name: 'Nokia 3.4 3GB RAM 64GB', path: './assets/images/homepage/phone/6.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 mini 128GB', path: './assets/images/homepage/phone/7.png'});
    this.imageSrc.push({name: 'Apple iPhone 11 Pro Max 256GB', path: './assets/images/homepage/phone/8.png'});
    this.imageSrc.push({name: 'Apple iPhone 11 Pro', path: './assets/images/homepage/phone/9.png'});
    this.imageSrc.push({name: 'Microsoft Lumia 950', path: './assets/images/homepage/phone/10.png'});
    this.imageSrc.push({name: 'Microsoft Lumia 950 XL Dual SIM', path: './assets/images/homepage/phone/11.png'});
    this.imageSrc.push({name: 'HTC Butterfly 3', path: './assets/images/homepage/phone/12.png'});
    this.imageSrc.push({name: 'HTC Desire 520', path: './assets/images/homepage/phone/13.png'});
    this.imageSrc.push({name: 'Blackberry KEYone ', path: './assets/images/homepage/phone/14.png'});
    this.imageSrc.push({name: 'Blackberry Leap', path: './assets/images/homepage/phone/15.png'});
    this.imageSrc.push({name: 'Google Pixel XL', path: './assets/images/homepage/phone/16.png'});
    this.imageSrc.push({name: 'Google Pixel XL', path: './assets/images/homepage/phone/17.png'});
    this.imageSrc.push({name: 'HTC One S9', path: './assets/images/homepage/phone/18.png'});
    this.imageSrc.push({name: 'Hp 15S – DU1086TU', path: './assets/images/homepage/laptop/16.png'});
    this.imageSrc.push({name: 'Hp 15S DU1025TX', path: './assets/images/homepage/laptop/17.png'});
    this.imageSrc.push({name: 'Hp 15S Du3022Tu – i3', path: './assets/images/homepage/laptop/18.png'});
    this.imageSrc.push({name: 'HP 15S-GU0008AU AMD Athlon', path: './assets/images/homepage/laptop/19.png'});
    this.imageSrc.push({name: 'HP EliteBook 830 G8 Notebook', path: './assets/images/homepage/laptop/20.png'});
    this.imageSrc.push({name: 'Hp Envy x360 Convertible 13-ar0120AU', path: './assets/images/homepage/laptop/21.png'});
    this.imageSrc.push({name: 'Hp Pavilion 15 – cs3049tx', path: './assets/images/homepage/laptop/22.png'});
    this.imageSrc.push({name: 'Hp Pavilion 15 – cs3050TX', path: './assets/images/homepage/laptop/23.png'});
    this.imageSrc.push({name: 'Hp Pavilion 15 – cs3051tx', path: './assets/images/homepage/laptop/24.png'});
    this.imageSrc.push({name: 'Hp Pavilion 15 – eg0112TX (i5)', path: './assets/images/homepage/laptop/25.png'});
    this.imageSrc.push({name: 'Hp Pavilion 15 – eg0121TX (i7)', path: './assets/images/homepage/laptop/26.png'});
    this.imageSrc.push({name: 'Hp Pavilion 16 – A0036TX Gaming Laptop', path: './assets/images/homepage/laptop/27.png'});
    this.imageSrc.push({name: 'Hp Pavilion Gaming 15 dk0217Tx', path: './assets/images/homepage/laptop/28.png'});
    this.imageSrc.push({name: 'Hp Pavilion Gaming Laptop 16-A0045TX', path: './assets/images/homepage/laptop/29.png'});
    this.imageSrc.push({name: 'Hp Pavilion x360 Convertible 14 (dw1029tu)', path: './assets/images/homepage/laptop/30.png'});
    this.imageSrc.push({name: 'HP ProBook 440 G8 Notebook', path: './assets/images/homepage/laptop/31.png'});
    this.imageSrc.push({name: 'HP ProBook 440 G8 Notebook', path: './assets/images/homepage/laptop/32.png'});
    this.imageSrc.push({name: 'HP ProBook 450 G7', path: './assets/images/homepage/laptop/33.png'});
    this.imageSrc.push({name: 'HP ProBook 450 G7 ', path: './assets/images/homepage/laptop/34.png'});
    this.imageSrc.push({name: 'HP ProBook 450 G8 Notebook', path: './assets/images/homepage/laptop/35.png'});
    this.imageSrc.push({name: 'HP ProBook 450 G8 Notebook', path: './assets/images/homepage/laptop/36.png'});
    this.imageSrc.push({name: 'HP ProBook 450 G8 Notebook', path: './assets/images/homepage/laptop/37.png'});
    this.imageSrc.push({name: 'HP Probook 455 G7 ', path: './assets/images/homepage/laptop/38.png'});
    this.imageSrc.push({name: 'HP Probook 455 G7 (Ryzen 7)', path: './assets/images/homepage/laptop/39.png'});
    this.imageSrc.push({name: 'HP ProBook x360 435 G7', path: './assets/images/homepage/laptop/40.png'});
    this.imageSrc.push({name: 'HP ProBook x360 435 G7 – R5', path: './assets/images/homepage/laptop/41.png'});
    this.imageSrc.push({name: 'HP ProBook x360 435 G7 Notebook PC', path: './assets/images/homepage/laptop/42.png'});
    this.imageSrc.push({name: 'HP Spectre X360 13 aw0196tu', path: './assets/images/homepage/laptop/43.png'});
    this.imageSrc.push({name: 'Hp Spectre X360 13-AW0254TU', path: './assets/images/homepage/laptop/44.png'});
    this.imageSrc.push({name: 'Asus VivoBook 15 M513UA', path: './assets/images/homepage/laptop/45.png'});
    this.imageSrc.push({name: 'Asus Expertbook B1500 ', path: './assets/images/homepage/laptop/46.png'});
    this.imageSrc.push({name: 'Asus Expertbook B1500', path: './assets/images/homepage/laptop/47.png'});
    this.imageSrc.push({name: 'Asus Expertbook B1500 ', path: './assets/images/homepage/laptop/48.png'});
    this.imageSrc.push({name: 'Asus Expertbook B1500', path: './assets/images/homepage/laptop/49.png'});
    this.imageSrc.push({name: 'Asus Expertbook L1500 ', path: './assets/images/homepage/laptop/50.png'});
    this.imageSrc.push({name: 'Asus Expertbook L1500 ', path: './assets/images/homepage/laptop/51.png'});
    this.imageSrc.push({name: 'ASUS ROG G512LU-( 242 i7 BLK/251 EPUNK )', path: './assets/images/homepage/laptop/52.png'});
    this.imageSrc.push({name: 'ASUS ROG G712LU-(709BLK)', path: './assets/images/homepage/laptop/53.png'});
    this.imageSrc.push({name: 'ASUS ROG Scar 17 (G733QM)', path: './assets/images/homepage/laptop/54.png'});
    this.imageSrc.push({name: 'ASUS ROG Strix SCAR 15 ', path: './assets/images/homepage/laptop/55.png'});
    this.imageSrc.push({name: 'Asus ROG Zephyrus Duo 15 SE GX551', path: './assets/images/homepage/laptop/56.png'});
    this.imageSrc.push({name: 'Asus ROG Zephyrus G14 GA401QM', path: './assets/images/homepage/laptop/57.png'});
    this.imageSrc.push({name: 'Asus ROG Zephyrus G15 GA503QM', path: './assets/images/homepage/laptop/58.png'});
    this.imageSrc.push({name: 'Asus ROG Zephyrus S15', path: './assets/images/homepage/laptop/59.png'});
    this.imageSrc.push({name: 'Asus Rog Zephyrus S15 Gx502lws', path: './assets/images/homepage/laptop/60.png'});
    this.imageSrc.push({name: 'Asus ROG Zephyrus S15 GX502LWS-HF135', path: './assets/images/homepage/laptop/61.png'});
    this.imageSrc.push({name: 'ASUS TUF Gaming A17', path: './assets/images/homepage/laptop/62.png'});
    this.imageSrc.push({name: 'ASUS TUF Gaming Dash F15 FX516PM', path: './assets/images/homepage/laptop/63.png'});
    this.imageSrc.push({name: 'Asus TUF GAMING F15', path: './assets/images/homepage/laptop/64.png'});
    this.imageSrc.push({name: 'ASUS TUF Gaming F17', path: './assets/images/homepage/laptop/65.png'});
    this.imageSrc.push({name: 'Asus Tuf Gaming FX506 HN117T ', path: './assets/images/homepage/laptop/66.png'});
    this.imageSrc.push({name: 'Asus Tuf Gaming FX506 HN117T (RTX Graphics)', path: './assets/images/homepage/laptop/67.png'});
    this.imageSrc.push({name: 'Asus TUF Gaming FX516PE-RTX3050Ti', path: './assets/images/homepage/laptop/68.png'});
    this.imageSrc.push({name: 'ASUS VivoBook S15 S533EQ', path: './assets/images/homepage/laptop/69.png'});
    this.imageSrc.push({name: 'ASUS VivoBook S15 S533EQ ', path: './assets/images/homepage/laptop/70.png'});
    this.imageSrc.push({name: 'ASUS VivoBook S15 S533EQ ', path: './assets/images/homepage/laptop/71.png'});
    this.imageSrc.push({name: 'ASUS VivoBook X513EP', path: './assets/images/homepage/laptop/72.png'});
    this.imageSrc.push({name: 'ASUS VivoBook X513EP', path: './assets/images/homepage/laptop/73.png'});
    this.imageSrc.push({name: 'ASUS ZenBook 14 UX425EA', path: './assets/images/homepage/laptop/74.png'});
    this.imageSrc.push({name: 'ASUS ZenBook 14 UX435EG', path: './assets/images/homepage/laptop/75.png'});
    this.imageSrc.push({name: 'ASUS ZenBook Duo 14 UX482EG ', path: './assets/images/homepage/laptop/76.png'});
    this.imageSrc.push({name: 'Asus Zenbook Flip 13 UX363', path: './assets/images/homepage/laptop/77.png'});
    this.imageSrc.push({name: 'Asus ZenBook Pro Duo 15 OLED UX582LR', path: './assets/images/homepage/laptop/78.png'});
    this.imageSrc.push({name: 'Asus Zenbook Pro Duo UX582', path: './assets/images/homepage/laptop/79.png'});
    this.imageSrc.push({name: 'AsusPro P2540FA-DM0485R', path: './assets/images/homepage/laptop/80.png'});
    this.imageSrc.push({name: 'ROG ZEPHYRUS G14 GA401 IU', path: './assets/images/homepage/laptop/81.png'});
    this.imageSrc.push({name: 'ROG Zephyrus M15', path: './assets/images/homepage/laptop/82.png'});
    this.imageSrc.push({name: 'Acer Predator Triton 300 15.6" IPS', path: './assets/images/homepage/laptop/83.png'});
    this.imageSrc.push({name: 'Acer Predator Triton 300 15.6" IPS', path: './assets/images/homepage/laptop/83.png'});
    this.imageSrc.push({name: 'Acer Aspire 3', path: './assets/images/homepage/laptop/84.png'});
    this.imageSrc.push({name: 'Acer Aspire 3 ', path: './assets/images/homepage/laptop/84.png'});
    this.imageSrc.push({name: 'Apple Z125000F1  ', path: './assets/images/homepage/laptop/85.png'});
    this.imageSrc.push({name: 'Apple Z125000GL', path: './assets/images/homepage/laptop/86.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 Pro Max 512GB', path: './assets/images/homepage/phone/apple/1.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 Pro Max 256GB', path: './assets/images/homepage/phone/apple/2.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 Pro Max 128GB', path: './assets/images/homepage/phone/apple/3.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 Pro 512GB', path: './assets/images/homepage/phone/apple/4.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 Pro 256GB', path: './assets/images/homepage/phone/apple/5.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 Pro 128GB', path: './assets/images/homepage/phone/apple/6.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 256GB', path: './assets/images/homepage/phone/apple/7.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 128GB', path: './assets/images/homepage/phone/apple/8.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 64GB', path: './assets/images/homepage/phone/apple/9.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 mini 128GB', path: './assets/images/homepage/phone/apple/10.png'});
    this.imageSrc.push({name: 'Apple iPhone 12 mini 64GB', path: './assets/images/homepage/phone/apple/11.png'});
    this.imageSrc.push({name: 'Apple iPhone SE (2020) 128GB', path: './assets/images/homepage/phone/apple/12.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S20 FE 5G', path: './assets/images/homepage/phone/samsung/1.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M12', path: './assets/images/homepage/phone/samsung/1.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M12', path: './assets/images/homepage/phone/samsung/2.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A32 ', path: './assets/images/homepage/phone/samsung/2.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A72', path: './assets/images/homepage/phone/samsung/3.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A72 ', path: './assets/images/homepage/phone/samsung/4.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A52', path: './assets/images/homepage/phone/samsung/5.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A12', path: './assets/images/homepage/phone/samsung/6.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A12', path: './assets/images/homepage/phone/samsung/6.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A32', path: './assets/images/homepage/phone/samsung/7.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M51', path: './assets/images/homepage/phone/samsung/8.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M02', path: './assets/images/homepage/phone/samsung/9.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S21 Ultra 5G', path: './assets/images/homepage/phone/samsung/10.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S21+ 5G', path: './assets/images/homepage/phone/samsung/11.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S21 5G', path: './assets/images/homepage/phone/samsung/12.png'});
    this.imageSrc.push({name: 'Samsung Galaxy Z Flip', path: './assets/images/homepage/phone/samsung/13.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M02s', path: './assets/images/homepage/phone/samsung/14.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M01s', path: './assets/images/homepage/phone/samsung/15.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A21s', path: './assets/images/homepage/phone/samsung/16.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S20 FE', path: './assets/images/homepage/phone/samsung/17.png'});
    this.imageSrc.push({name: 'Samsung Galaxy Z Fold2 5G', path: './assets/images/homepage/phone/samsung/18.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A71 ', path: './assets/images/homepage/phone/samsung/19.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A51', path: './assets/images/homepage/phone/samsung/20.png'});
    this.imageSrc.push({name: 'Samsung Galaxy Note20 Ultra 5G', path: './assets/images/homepage/phone/samsung/21.png'});
    this.imageSrc.push({name: 'Samsung Galaxy Note20', path: './assets/images/homepage/phone/samsung/22.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M31', path: './assets/images/homepage/phone/samsung/23.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M21 ', path: './assets/images/homepage/phone/samsung/24.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M01 Core', path: './assets/images/homepage/phone/samsung/25.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A21s', path: './assets/images/homepage/phone/samsung/26.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M01', path: './assets/images/homepage/phone/samsung/27.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M21 ', path: './assets/images/homepage/phone/samsung/28.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M11', path: './assets/images/homepage/phone/samsung/29.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M31', path: './assets/images/homepage/phone/samsung/30.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A11', path: './assets/images/homepage/phone/samsung/31.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S20 Ultra', path: './assets/images/homepage/phone/samsung/32.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S20+', path: './assets/images/homepage/phone/samsung/33.png'});
    this.imageSrc.push({name: 'Samsung Galaxy S20', path: './assets/images/homepage/phone/samsung/34.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A01', path: './assets/images/homepage/phone/samsung/35.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A71', path: './assets/images/homepage/phone/samsung/36.png'});
    this.imageSrc.push({name: 'Samsung Galaxy Note10 Lite', path: './assets/images/homepage/phone/samsung/37.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A51', path: './assets/images/homepage/phone/samsung/38.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A70s', path: './assets/images/homepage/phone/samsung/39.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A30s', path: './assets/images/homepage/phone/samsung/40.png'});
    this.imageSrc.push({name: 'Samsung Galaxy M30s', path: './assets/images/homepage/phone/samsung/41.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A20s ', path: './assets/images/homepage/phone/samsung/42.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A50s', path: './assets/images/homepage/phone/samsung/43.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A30s', path: './assets/images/homepage/phone/samsung/44.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A10s', path: './assets/images/homepage/phone/samsung/45.png'});
    this.imageSrc.push({name: 'Samsung Galaxy Note10+', path: './assets/images/homepage/phone/samsung/46.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A80', path: './assets/images/homepage/phone/samsung/47.png'});
    this.imageSrc.push({name: 'Samsung Galaxy A80', path: './assets/images/homepage/phone/samsung/48.png'});
    this.imageSrc.push({name: 'Nokia C20 ', path: './assets/images/homepage/phone/nokia/1.png'});
    this.imageSrc.push({name: 'Nokia 3.4', path: './assets/images/homepage/phone/nokia/2.png'});
    this.imageSrc.push({name: 'Nokia 1.4', path: './assets/images/homepage/phone/nokia/3.png'});
    this.imageSrc.push({name: 'Nokia 5.4 ', path: './assets/images/homepage/phone/nokia/4.png'});
    this.imageSrc.push({name: 'Nokia C1 Plus', path: './assets/images/homepage/phone/nokia/5.png'});
    this.imageSrc.push({name: 'Nokia 3.4', path: './assets/images/homepage/phone/nokia/6.png'});
    this.imageSrc.push({name: 'Nokia 150', path: './assets/images/homepage/phone/nokia/7.png'});
    this.imageSrc.push({name: 'Nokia 5310', path: './assets/images/homepage/phone/nokia/8.png'});
    this.imageSrc.push({name: 'Nokia 220 4G', path: './assets/images/homepage/phone/nokia/9.png'});
    this.imageSrc.push({name: 'Nokia 2.4', path: './assets/images/homepage/phone/nokia/10.png'});
    this.imageSrc.push({name: 'Nokia 5.3', path: './assets/images/homepage/phone/nokia/11.png'});
    this.imageSrc.push({name: 'Nokia 110', path: './assets/images/homepage/phone/nokia/12.png'});
    this.imageSrc.push({name: 'Nokia 105 ', path: './assets/images/homepage/phone/nokia/13.png'});
    this.imageSrc.push({name: 'Nokia 210', path: './assets/images/homepage/phone/nokia/14.png'});
    this.imageSrc.push({name: 'Nokia 7.2', path: './assets/images/homepage/phone/nokia/15.png'});
    this.imageSrc.push({name: 'HTC One A9s', path: './assets/images/homepage/phone/htc/1.png'});
    this.imageSrc.push({name: 'HTC Desire 650', path: './assets/images/homepage/phone/htc/2.png'});


  }

}
